[[redirects]]
  from = "/"
  to = "https://kmapshot.com"
  status = 301
  force = true

[[redirects]]
  from = "/manual/index.html"
  to = "https://kmapshot.com/manual/0"
  status = 301
  force = true

[[redirects]]
  from = "/log/index.html"
  to = "https://kmapshot.com/notice/1"
  status = 301
  force = true

[[redirects]]
  from = "/contact/index.html"
  to = "https://kmapshot.com/contact"
  status = 301
  force = true